name: flutter_application_5
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  http: ^1.2.0
  get_it: ^7.2.0
  flutter_bloc: ^8.1.5
  flutter_riverpod: ^2.5.1
  path_provider: ^2.0.2
  flutter_cache_manager: ^3.1.2
  webview_flutter: ^2.0.12
  shared_preferences: ^2.0.6
  fl_chart: ^0.40.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
